import { useEffect, useState } from 'react';
import { listarProdutos } from '../../servicos/produtoService';
import { listarPerguntas, responderPergunta } from '../../servicos/perguntaService';

export default function Perguntas() {
  const [produtos, setProdutos] = useState([]); const [produtoId, setProdutoId] = useState(''); const [perguntas, setPerguntas] = useState([]); const [respostas, setRespostas] = useState({}); const [erro, setErro] = useState(''); const [salvando, setSalvando] = useState(null);
  useEffect(() => { listarProdutos().then((dados) => { setProdutos(dados); if (dados[0]) setProdutoId(String(dados[0].id)); }).catch((e) => setErro(e.message)); }, []);
  async function carregar(id = produtoId) { if (!id) return; try { setErro(''); setPerguntas(await listarPerguntas(id)); } catch (e) { setErro(e.message); } }
  useEffect(() => { carregar(); }, [produtoId]);
  async function salvar(pergunta) { const resposta = (respostas[pergunta.id] ?? pergunta.resposta ?? '').trim(); if (resposta.length < 2) { setErro('Escreva uma resposta com pelo menos 2 caracteres.'); return; } setSalvando(pergunta.id); try { await responderPergunta(pergunta.id, resposta); setRespostas((atual) => ({ ...atual, [pergunta.id]: resposta })); await carregar(); } catch (e) { setErro(e.message); } finally { setSalvando(null); } }
  const produtoSelecionado = produtos.find((produto) => String(produto.id) === produtoId);
  const categorias = [...new Set(produtos.map((produto) => produto.categoria || 'Sem categoria'))].sort();
  return <main className="mx-auto max-w-4xl px-4 py-8"><h1 className="text-2xl font-bold">Perguntas de produtos</h1><p className="mt-2 text-sm text-gray-500">Responda dúvidas dos clientes para ajudar na decisão de compra.</p>{erro && <p role="alert" className="mt-4 rounded bg-red-50 p-3 text-red-700">{erro}</p>}<section className="mt-6 flex flex-col gap-3 rounded-lg border border-[#2b2618] bg-[#111210] p-5 shadow-sm sm:flex-row sm:items-end"><label className="min-w-0 flex-1 text-sm font-semibold text-[#f4efe5]">Produto ativo<select value={produtoId} onChange={(e) => setProdutoId(e.target.value)} className="mt-2 block w-full rounded border border-[#3a3526] bg-[#181915] px-3 py-2.5 text-[#f4efe5] focus:border-[#d4af45] focus:outline-none">{categorias.map((categoria) => <optgroup key={categoria} label={categoria}>{produtos.filter((produto) => (produto.categoria || 'Sem categoria') === categoria).map((produto) => <option key={produto.id} value={produto.id}>{produto.nome}</option>)}</optgroup>)}</select></label>{produtoSelecionado && <div className="rounded border border-[#3a3526] bg-[#181915] px-4 py-2.5 text-sm text-[#c6c0b5]"><span className="text-xs uppercase tracking-wide text-[#aaa396]">Selecionado</span><strong className="ml-2 text-[#d4af45]">{produtoSelecionado.nome}</strong></div>}</section><section className="mt-6 space-y-4">{perguntas.length ? perguntas.map((pergunta) => <article key={pergunta.id} className="rounded-lg bg-white p-5 shadow"><p className="font-semibold">Pergunta de {pergunta.usuario_nome}</p><p className="mt-2 text-gray-700">{pergunta.pergunta}</p><label className="mt-4 block text-sm font-semibold">Resposta da loja<textarea value={respostas[pergunta.id] ?? pergunta.resposta ?? ''} onChange={(e) => setRespostas((atual) => ({ ...atual, [pergunta.id]: e.target.value }))} maxLength="1000" className="mt-2 min-h-24 w-full rounded border p-2" placeholder="Escreva uma resposta clara e objetiva" /></label><button type="button" onClick={() => salvar(pergunta)} disabled={salvando === pergunta.id} className="mt-3 rounded bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{salvando === pergunta.id ? 'Salvando...' : pergunta.resposta ? 'Atualizar resposta' : 'Publicar resposta'}</button></article>) : <p className="rounded bg-white p-6 text-center text-gray-500 shadow">Não há perguntas para este produto.</p>}</section></main>;
}
