ALTER TABLE banners
  ADD COLUMN imagem_url_2 VARCHAR(500) NOT NULL DEFAULT '',
  ADD COLUMN posicao_x_2 TINYINT UNSIGNED NOT NULL DEFAULT 50,
  ADD COLUMN posicao_y_2 TINYINT UNSIGNED NOT NULL DEFAULT 50,
  ADD COLUMN principal BOOLEAN NOT NULL DEFAULT FALSE;
